build-linux:
  stage: build
  image: $CI_REGISTRY/nicolas17/openssl-sspi/build:linux
  script:
    - mkdir build
    - cd build
    - cmake .. -G Ninja
    - ninja

build-mingw:
  stage: build
  image: $CI_REGISTRY/nicolas17/openssl-sspi/build:mingw
  script:
    - mkdir build
    - cd build
    - cmake .. -G Ninja -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_PREFIX_PATH=$HOME/dist
    - ninja

build-msvc2017:
  stage: build
  tags:
    - msvc2017
  script:
    - call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - mkdir build
    - cd build
    - cmake .. -G "NMake Makefiles" -DCMAKE_TOOLCHAIN_FILE=C:\GitLabRunner\vcpkg\scripts\buildsystems\vcpkg.cmake
    - nmake
